version: '3'
services:
  worker:
    build: .
    command: invoke monitor
    links:
      - mongo
    environment:
      STORAGE_URI: mongodb://user:pass@mongo:27017/

  mongo:
    image: "mongo:3.7"
    ports:
      - "27017:27017"
    environment:
      MONGODB_USER: "user"
      MONGODB_PASS: "pass"
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /dev/null
    volumes:
      - ./data/db:/data/db
