version: '2'
services:
  migrate:
    build: .
    command: python tasks.py db upgrade head
    links:
      - database
    environment:
      DB_URL: postgres://${PG_USER}:${PG_PASS}@database/${PG_DB}

  frontend:
    build: .
    command: python tasks.py web
    links:
      - database
    depends_on:
      - "migrate"
    environment:
      JWT_SECRET: ${JWT_SECRET}
      DB_URL: postgres://${PG_USER}:${PG_PASS}@database/${PG_DB}

  worker:
    build: .
    command: python tasks.py monitor
    links:
      - database
    depends_on:
      - "migrate"
    environment:
      DB_URL: postgres://${PG_USER}:${PG_PASS}@database/${PG_DB}

  database:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
      PGDATA: /data/db
    volumes:
      - ./data/db:/data/db
