version: '2'
services:
  frontend:
    build: .
    command: invoke web
    links:
      - database
    environment:
      DB_HOST: database
      DB_PASSWORD: ${PG_PASS}
      API_PASSWORD: ${API_PASS}

  worker:
    build: .
    command: invoke monitor
    links:
      - database
    environment:
      DB_HOST: database
      DB_PASSWORD: ${PG_PASS}
      TESLA_EMAIL: ${TESLA_EMAIL}
      TESLA_PASS: ${TESLA_PASS}

  database:
    image: "postgres:latest"
    environment:
      POSTGRES_DB: tesla
      POSTGRES_USER: tesla
      POSTGRES_PASSWORD: ${PG_PASS}
      PGDATA: /data/db
    volumes:
      - ./data/db:/data/db
