version: '3'
services:
  worker:
    build: .
    command: invoke monitor
    links:
      - mongo
    environment:
      DB_HOST: database
      DB_PASSWORD: ${PG_PASS}

  database:
    image: "postgres:latest"
    environment:
      POSTGRES_DB: tesla
      POSTGRES_USER: tesla
      POSTGRES_PASSWORD: ${PG_PASS}
      PGDATA: /data/db
    volumes:
      - ./data/db:/data/db
