"""empty message

Revision ID: 0373a0f244aa
Revises: bd099d63f4b3
Create Date: 2018-02-13 20:58:04.985820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0373a0f244aa'
down_revision = 'bd099d63f4b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(), nullable=True),
        sa.Column('password_hash', sa.String(), nullable=True),
        sa.Column('tesla_access_token', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_table('vehicle',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tesla_id', sa.String(), nullable=False),
        sa.Column('vin', sa.String(), nullable=True),
        sa.Column('color', sa.String(), nullable=True),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('next_update_time', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_index(op.f('ix_vehicle_tesla_id'), 'vehicle', ['tesla_id'], unique=False)
    op.add_column('charge_state', sa.Column('vehicle_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'charge_state', 'vehicle', ['vehicle_id'], ['id'])
    op.add_column('climate_state', sa.Column('vehicle_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'climate_state', 'vehicle', ['vehicle_id'], ['id'])
    op.add_column('drive_state', sa.Column('vehicle_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'drive_state', 'vehicle', ['vehicle_id'], ['id'])
    op.add_column('vehicle_state', sa.Column('vehicle_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'vehicle_state', 'vehicle', ['vehicle_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicle_state', type_='foreignkey')
    op.drop_column('vehicle_state', 'vehicle_id')
    op.drop_constraint(None, 'drive_state', type_='foreignkey')
    op.drop_column('drive_state', 'vehicle_id')
    op.drop_constraint(None, 'climate_state', type_='foreignkey')
    op.drop_column('climate_state', 'vehicle_id')
    op.drop_constraint(None, 'charge_state', type_='foreignkey')
    op.drop_column('charge_state', 'vehicle_id')
    op.drop_index(op.f('ix_vehicle_tesla_id'), table_name='vehicle')
    op.drop_table('vehicle')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
